### ISSUE TITLE
GenAI Scenario Deployment Broken

### ISSUE THREAD

**Issue by samaea** [Azure/apim-landing-zone-accelerator#132] opened 2024-08-05 10:10 UTC
The GenAI Scenario fails to deploy via GitHub workspaces and locally with the following error message:-

ERROR: (", AttributeError: 'str' object has no attribute 'get' 'Unable to deserialize to object: type' , AttributeError(" 'str object has no attribute 'get' " ) ) sam@[REDACTED]/ : /mnt/c/Users/[REDACTED]/Downloads/apimgenaigateway/apim-landing-zone-accelerator/scenarios$

![image](https://github.com/user-attachments/assets/cf001525-5060-4e12-bee1-37c89db2d27e)

**Comment by aarthiem** [comment] 2024-10-23 16:00
closing the issue based on the confirmation from @samaea that the issue is due to the subscription that could have disabled the functionality

**Closed** 2024-10-23 16:00 UTC
